<?php require_once( "../dld89430upsnmUDCX/cms.php" ); ?>
<cms:template title="Advertise"></cms:template>
<!doctype html>
<!--
      _                             __                 _____  _____       __                        
     / \                           [  |               |_   _||_   _|     [  |                       
    / _ \     _ .--.   .--.  .---.  | |  _ .--..--.     | |    | | _ .--. | |.--.   ,--.   _ .--.   
   / ___ \   [ `.-. | ( (`\]/ /__\\ | | [ `.-. .-. |    | '    ' |[ `/'`\]| '/'`\ \`'_\ : [ `.-. |  
 _/ /   \ \_  | | | |  `'.'.| \__., | |  | | | | | |     \ \__/ /  | |    |  \__/ |// | |, | | | |  
|____| |____|[___||__][\__) )'.__.'[___][___||__||__]     `.__.'  [___]  [__;.__.' \'-;__/[___||__] 
                                                                                                    
-->
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>Advertise with HTML5Sites for only 25$ per month! – A curated gallery of sites about HTML5</title>
		<meta name="description" content="Advertise with HTML5Sites for only 25$ per month! – A curated gallery of sites about HTML5. Here you can find lots of tutorials, demos, and other interesting stuff, also in other languages. The gallery can be sorted by category, language or keywords.">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
		<meta name="google" content="notranslate">
		<meta property="og:title" content="Advertise with HTML5Sites – A curated gallery of sites about HTML5">
		<meta property="og:type" content="website">
		<meta property="og:url" content="https://html5sit.es/advertise/">
		<meta property="og:image" content="https://html5sit.es/img/bg-logo.png">
		<meta name="twitter:card" content="summary_large_image">
		<meta name="twitter:site" content="@HTML5Sit_es">
		<meta name="twitter:creator" content="@HTML5Sit_es">
		<meta name="twitter:title" content="Advertise with HTML5Sites for only 25$ per month! – A curated gallery of sites about HTML5">
		<meta name="twitter:description" content="Advertise with HTML5Sites for only 25$ per month! – A curated gallery of sites about HTML5. Here you can find lots of tutorials, demos, and other interesting stuff, also in other languages. The gallery can be sorted by category, language or keywords.">
		<meta name="twitter:image" content="https://html5sit.es/logo.png">
		<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
		<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
		<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
		<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
		<link rel="manifest" href="/manifest.json">
		<meta name="apple-mobile-web-app-title" content="HTML5Sites">
		<meta name="application-name" content="HTML5Sites">
		<meta name="msapplication-TileColor" content="#e44d26">
		<meta name="msapplication-TileImage" content="/mstile-144x144.png">
		<meta name="msapplication-tap-highlight" content="no">
		<meta name="theme-color" content="#e44d26">
		<script src="https://use.edgefonts.net/source-sans-pro:n3,n4,i4,n6:all.js" async></script>
		<style>
			/*! Generated by Font Squirrel (http://www.fontsquirrel.com) on July 15, 2015*/@font-face{font-family:"big_johnregular";src:url(../fonts/big_john-webfont.eot);src:url(../fonts/big_john-webfont.eot?#iefix) format("embedded-opentype"),url(../fonts/big_john-webfont.woff2) format("woff2"),url(../fonts/big_john-webfont.woff) format("woff"),url(../fonts/big_john-webfont.ttf) format("truetype"),url(../fonts/big_john-webfont.svg#big_johnregular) format("svg");font-weight:400;font-style:normal}@font-face{font-family:"slim_joeregular";src:url(../fonts/slim_joe-webfont.eot);src:url(../fonts/slim_joe-webfont.eot?#iefix) format("embedded-opentype"),url(../fonts/slim_joe-webfont.woff2) format("woff2"),url(../fonts/slim_joe-webfont.woff) format("woff"),url(../fonts/slim_joe-webfont.ttf) format("truetype"),url(../fonts/slim_joe-webfont.svg#slim_joeregular) format("svg");font-weight:400;font-style:normal}
			html,body,div,span,iframe,h1,h2,p,a,img,strong,i,center,ul,li,form,label,article,footer,header{margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;border-top-width:0;border-right-width:0;border-bottom-width:0;border-left-width:0;border-style:initial;border-color:initial;font-size:100%;font:inherit;vertical-align:baseline}article,footer,header,main{display:block}ul{list-style-type:none;list-style-position:initial;list-style-image:initial}html{color:#222;font-size:1em;line-height:1.4}iframe,img{vertical-align:middle}textarea{resize:vertical}*{text-rendering:optimizelegibility;-webkit-font-smoothing:antialiased!important;box-sizing:border-box}html.touch *,html.touch :before,html.touch :after{text-rendering:optimizespeed}html{font-size:62.5%}body:before,body:after{display:block;content:""}body{width:100%;height:100%;font-size:1.5rem;font-family:source-sans-pro,sans-serif;background-image:url(../img/bg-top.png);background-attachment:initial;background-origin:initial;background-clip:initial;background-color:initial;padding-top:50px;padding-right:0;padding-bottom:50px;padding-left:0;z-index:0;background-position:50% 0;background-repeat:no-repeat no-repeat}h1,h2{text-align:center;font-weight:400;font-family:big_johnregular,sans-serif}h2{font-size:1.8rem;margin-top:.83em;margin-right:0;margin-bottom:.83em;margin-left:0}h1,h2{cursor:default}p{text-align:justify}a{text-decoration:none;color:#e44d26}iframe{border-top-width:0;border-right-width:0;border-bottom-width:0;border-left-width:0;border-style:initial;border-color:initial}strong{font-weight:600}input,button{font-size:1.5rem;font-family:source-sans-pro,sans-serif}#header{padding-top:0;padding-right:15px;padding-bottom:0;padding-left:15px}#header-logo{width:100%;max-width:256px;margin-top:0;margin-right:auto;margin-bottom:0;margin-left:auto}#header-logo a{display:inline-block}#header-logo img{width:100%;pointer-events:none}#article{max-width:45em;margin-top:0;margin-right:auto;margin-bottom:0;margin-left:auto;padding-top:1em;padding-right:1em;padding-bottom:1em;padding-left:1em}#article p,#article ul{font-size:1.8rem}#article p{margin-top:1em;margin-right:0;margin-bottom:1em;margin-left:0}#footer{border-top-width:1px;border-top-style:solid;border-top-color:#e2e2e2;padding-top:0;padding-right:5%;padding-bottom:0;padding-left:5%}#footer p{padding-top:1em;padding-right:1em;padding-bottom:1em;padding-left:1em;color:#e44d26;text-align:center;font-size:1.3rem}#footer p a{color:#e44d26;text-decoration:none;font-weight:600}@media only screen and (min-width:40em){h2{font-size:2.4rem}}@media only screen and (min-width:768px){#footer{padding-top:0;padding-right:3%;padding-bottom:0;padding-left:3%}}@media only screen and (min-width:1170px){#footer{padding-top:0;padding-right:2%;padding-bottom:0;padding-left:2%}}.visuallyhidden{border-top-width:0;border-right-width:0;border-bottom-width:0;border-left-width:0;border-style:initial;border-color:initial;clip:rect(0 0 0 0);height:1px;margin-top:-1px;margin-right:-1px;margin-bottom:-1px;margin-left:-1px;overflow-x:hidden;overflow-y:hidden;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;position:absolute;width:1px}@media print{*{background-image:initial!important;background-attachment:initial!important;background-origin:initial!important;background-clip:initial!important;background-color:transparent!important;color:#000!important;box-shadow:none!important;text-shadow:none!important;background-position:initial initial!important;background-repeat:initial initial!important}a{text-decoration:underline}a[href]:after{content:" (",attr(href),")"}a[href^="#"]:after{content:""}img{page-break-inside:avoid;max-width:100%!important}p,h2{orphans:3;widows:3}h2{page-break-after:avoid}}.fa{display:inline-block;font:normal normal normal 14px/1 FontAwesome;font-size:inherit;text-rendering:auto;-webkit-font-smoothing:antialiased}.fa-ul{padding-left:0;margin-left:2.14285714em;list-style-type:none}.fa-ul>li{position:relative}.fa-li{position:absolute;left:-2.14285714em;width:2.14285714em;top:.14285714em;text-align:center}
		</style>
		<script>
			/*!
			loadCSS: load a CSS file asynchronously.
			[c]2014 @scottjehl, Filament Group, Inc.
			Licensed MIT
			*/
			function loadCSS(f,b,g,c){var a=window.document.createElement("link");b=b||window.document.getElementsByTagName("script")[0];var e=window.document.styleSheets;a.rel="stylesheet";a.href=f;a.media="only x";c&&(a.onload=c);b.parentNode.insertBefore(a,b);a.onloadcssdefined=function(b){for(var c,d=0;d<e.length;d++)e[d].href&&e[d].href===a.href&&(c=!0);c?b():setTimeout(function(){a.onloadcssdefined(b)})};a.onloadcssdefined(function(){a.media=g||"all"});return a}
			loadCSS("../css/main.css");
		</script>
		<noscript><link rel="stylesheet" href="../css/main.css"></noscript>
		<link rel="prefetch" href="../">
		<link rel="prerender" href="../">
	</head>
	<body>
		<header id="header">
			<h1 id="header-logo"><a href="../"><img src="../logo.svg" alt="Logo"><br><span class="visuallyhidden">HTML5Sites</span></a></h1>
			<h2>curated gallery of sites about HTML5</h2>
		</header>
        <main>
			<article id="article">
				<cms:editable name="Main" type="textarea">
					<h2 style="font-size: 1.8rem;">Advertise with HTML5Sites</h2>
					<p><strong>Do you want to expose your awesome website, blog or other project to a broader audience?</strong></p>
					<p>By featuring your site on <a href="../">HTML5Sites</a>, you make sure that thousands of web designers and developers from all over the world get to know your site (and may become clients).</p>
					<p>
						Your ad will be part of the gallery but it will always be visible no matter what category users select and your ad will always be the first item in the gallery.<br>
						Availability and Scheduling:
						<ul class="fa-ul">
							<li><i class="fa-li fa fa-chevron-right"></i>There are two available ad slots per month</li>
							<li><i class="fa-li fa fa-chevron-right"></i>Ads run for one month</li>
						</ul>
					</p>
					<p>Starting at 25$ per month. <strong><a href="mailto:hello@html5sit.es" itemprop="email">Get in touch now <i class="fa fa-chevron-right"></i></a></strong></p>
				</cms:editable>
			</article>
        </main>
        <footer id="footer" style="max-width: 45em; margin: 0 auto;">
			<p>
				© <script>2010<(new Date).getFullYear()&&document.write((new Date).getFullYear());</script> <a href="https://anselmurban.de/?utm_source=HTML5Sites&utm_medium=referral"><span itemprop="name">Anselm Urban</span> <i class="fa fa-external-link"></i></a> • 
				<a href="mailto:hello@html5sit.es" itemprop="email">hello@html5sit.es</a> • 
				<a href="https://www.iubenda.com/privacy-policy/388465" class="iubenda-black iubenda-embed" title="Privacy Policy" rel="nofollow">Privacy Policy <i class="fa fa-external-link"></i></a> • 
				Hosted by <a href="https://pixeno.com/account/aff.php?aff=054" rel="nofollow">Pixeno <i class="fa fa-external-link"></i></a>
			</p>
		</footer>

		<script src="../js/vendor/prefixfree.js"></script>
		<script src="../js/vendor/modernizr-2.8.3.min.js"></script>
		<script data-cfasync="false" src="https://fast.eager.io/cw6jSdfMhqvO.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../js/vendor/jquery-2.1.4.min.js"><\/script>')</script>
		<script src="../js/plugins.js"></script>
		<script src="../js/main.js"></script>
		<script src="https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55a61618f37e0e47" async></script>
		<script src="https://load.sumome.com/" data-sumo-site-id="10a215e5f7848d2f6654014040b87150f180bd042eb62ad0cb3792d6fe75c22d" async></script>
		<script type="text/javascript">
		  var vglnk = { key: 'e60f27433682e994e8abc2c4c91302cc' };

		  (function(d, t) {
			var s = d.createElement(t); s.type = 'text/javascript'; s.async = true;
			s.src = '//cdn.viglink.com/api/vglnk.js';
			var r = d.getElementsByTagName(t)[0]; r.parentNode.insertBefore(s, r);
		  }(document, 'script'));
		</script>
		<script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-50648234-14','auto');ga('send','pageview');
        </script>
    </body>
</html>
<?php COUCH::invoke(); ?>
